import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  gestureShell: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  headerShell: {
    backgroundColor: '#fff',
  },
  header: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logo: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginRight: 10,
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  headerMenuButton: {
    width: 44,
    height: 44,
    marginLeft: 8,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
  },
  menuOverlayBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    alignItems: 'flex-end',
    paddingTop: 8,
    paddingRight: 20,
  },
  menuOverlayRoot: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  menuPanel: {
    position: 'absolute',
    top: 64,
    right: 20,
    backgroundColor: '#fff',
    borderRadius: 12,
    minWidth: 240,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemLabel: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  legalScreen: {
    flex: 1,
    backgroundColor: '#fff',
  },
  legalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  legalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
    flex: 1,
  },
  legalCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
  },
  legalScroll: {
    flex: 1,
  },
  legalScrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingBottom: 32,
  },
  legalIntro: {
    fontSize: 14,
    lineHeight: 20,
    color: '#666',
    marginBottom: 20,
  },
  legalSection: {
    marginBottom: 24,
  },
  legalSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 10,
  },
  legalParagraph: {
    fontSize: 15,
    lineHeight: 22,
    color: '#444',
    marginBottom: 10,
  },
  helpSteps: {
    gap: 10,
    marginBottom: 12,
  },
  helpStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  helpStepBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  helpStepBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2196F3',
  },
  helpStepText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: '#444',
  },
  helpLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
    paddingVertical: 12,
  },
  helpLinkButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2196F3',
  },
  notificationStatusCard: {
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    gap: 14,
  },
  notificationStatusBlock: {
    gap: 4,
  },
  notificationStatusLabel: {
    fontSize: 13,
    color: '#666',
    marginBottom: 4,
  },
  notificationStatusValue: {
    fontSize: 17,
    fontWeight: '600',
    color: '#333',
  },
  notificationStatusHint: {
    fontSize: 13,
    lineHeight: 18,
    color: '#C62828',
    marginTop: 4,
  },
  notificationSection: {
    marginTop: 8,
    marginBottom: 16,
  },
  notificationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  notificationRowText: {
    flex: 1,
  },
  notificationRowLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  notificationRowDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: '#666',
  },
  notificationSystemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2196F3',
    backgroundColor: '#fff',
  },
  notificationSystemButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2196F3',
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  searchOverlayRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  searchOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
  },
  searchOverlayPanel: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: 48,
  },
  searchOverlayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchOverlayTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#333',
  },
  searchOverlayCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
  },
  searchOverlaySearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  searchOverlayCount: {
    fontSize: 14,
    color: '#666',
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    backgroundColor: '#f8f8f8',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2196F3',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  iconButtonActive: {
    backgroundColor: '#2196F3',
  },
  mainContent: {
    flex: 1,
  },
  mapFull: {
    flex: 1,
  },
  mapAboveStrip: {
    flex: 1,
    marginBottom: 142,
  },
  mapContainer: {
    flex: 1,
    paddingTop: 0,
    position: 'relative',
  },
  detailStrip: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingBottom: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  detailStripMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 36,
    paddingLeft: 28,
    paddingRight: 14,
  },
  detailStripNumber: {
    fontSize: 46,
    fontWeight: 'bold',
    color: '#2196F3',
    minWidth: 80,
    maxWidth: 96,
    textAlign: 'center',
    marginRight: 18,
  },
  detailStripInfo: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  detailStripName: {
    fontSize: 28,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
  },
  detailStripRegion: {
    fontSize: 18,
    color: '#666',
  },
  detailStripMatch: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E91E63',
  },
  detailStripCloseButton: {
    width: 64,
    height: 64,
    marginRight: 10,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
  },
  locationHeart: {
    marginLeft: 8,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: 20,
  },
  item: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginVertical: 5,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  itemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
  },
  itemNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2196F3',
    minWidth: 50,
    textAlign: 'center',
    marginRight: 15,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  itemRegion: {
    fontSize: 14,
    color: '#666',
  },
  itemMatch: {
    fontSize: 14,
    fontWeight: '600',
    color: '#E91E63',
  },
});
